version:"3.8"

services:
  backend:
    image : backend
    container_name : chatbackend
    ports:
      - "8080:8080"

  frontend:
    image : frontend
    container_name : chatfrontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
  

